#!/bin/bash
ip=$1
port=$2
gwport=$3
gw=$4
rate=$5
node /home/device.js --local_ip $ip --local_port $port --local_name "${gw}dev1" --remote_ip=$ip --remote_port $gwport  --remote_name $gw --send_period $rate &

node /home/device.js --local_ip $ip --local_port $((port+1)) --local_name "${gw}dev2" --remote_ip=$ip --remote_port $gwport  --remote_name $gw --send_period $rate &

node /home/device.js --local_ip $ip --local_port $((port+2)) --local_name "${gw}dev3" --remote_ip=$ip --remote_port $gwport  --remote_name $gw --send_period $rate &
